#!/usr/bin/env python3
"""
Generate Kubernetes manifests with Linguistic Sovereignty naming.

This script creates Kubernetes YAML files with tripartite naming
(Linear A ↔ Hebrew ↔ Egyptian) for sovereign infrastructure.

Usage:
    python generate_k8s_manifests.py [--output-dir PATH] [--seed INT]
"""

import argparse
import os
import sys

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from linguistic_sovereignty import LinguisticSovereignty


NAMESPACE_TEMPLATE = """# Generated by Linguistic Sovereignty Framework
# Namespace: {function}
# Poetic Name: {poetic_name}
# Glyph: {glyph}

apiVersion: v1
kind: Namespace
metadata:
  name: {namespace}
  labels:
    strategickhaos.io/poetic-name: "{poetic_name}"
    strategickhaos.io/glyph: "{glyph}"
    strategickhaos.io/hebrew-root: "{hebrew_root}"
    strategickhaos.io/egyptian-seal: "{egyptian_seal}"
    strategickhaos.io/semantic-field: "{semantic_field}"
    strategickhaos.io/priority: "{priority}"
    app.kubernetes.io/component: "{component_type}"
    app.kubernetes.io/function: "{function}"
    app.kubernetes.io/part-of: "sovereignty-architecture"
    app.kubernetes.io/managed-by: "linguistic-sovereignty-framework"
  annotations:
    strategickhaos.io/cryptographic-strength: "SHA-256"
    strategickhaos.io/sovereign-status: "ZERO_VENDOR_LOCK_IN"
---
"""

SERVICE_TEMPLATE = """apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  namespace: {namespace}
  labels:
    strategickhaos.io/function: "{function}"
    strategickhaos.io/poetic-alias: "{poetic_name}"
    strategickhaos.io/glyph: "{glyph}"
    app.kubernetes.io/name: "{service_name}"
    app.kubernetes.io/component: "{component_type}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {function}
---
"""


def generate_manifests(output_dir: str, seed: int = 42) -> None:
    """Generate Kubernetes manifests with sovereign naming.
    
    Args:
        output_dir: Directory to write manifest files
        seed: Random seed for reproducible naming
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Initialize framework
    sovereignty = LinguisticSovereignty(seed=seed)
    
    # Build mappings
    rosetta = sovereignty.build_tripartite_rosetta()
    k8s = sovereignty.map_to_kubernetes_architecture()
    
    # Generate namespace manifests
    all_namespaces = []
    
    for function, ns_config in k8s["namespaces"].items():
        glyph = ns_config["glyph"]
        labels = ns_config["labels"]
        
        # Get semantic field from vector
        if glyph in sovereignty.glyph_vectors:
            vec = sovereignty.glyph_vectors[glyph]
            semantic_field = sovereignty._derive_semantic_field(vec)
        else:
            semantic_field = "default-field"
        
        namespace_yaml = NAMESPACE_TEMPLATE.format(
            function=function,
            namespace=ns_config["name"],
            poetic_name=ns_config["poetic_alias"],
            glyph=glyph,
            hebrew_root=labels.get("strategickhaos.io/hebrew-root", "unknown"),
            egyptian_seal=labels.get("strategickhaos.io/egyptian-seal", "unknown"),
            semantic_field=semantic_field,
            priority=labels.get("strategickhaos.io/priority", "medium"),
            component_type=labels.get("app.kubernetes.io/component", "unknown")
        )
        
        # Add service
        service_name = f"{function.replace('_', '-')}-svc"
        service_yaml = SERVICE_TEMPLATE.format(
            service_name=service_name,
            namespace=ns_config["name"],
            function=function,
            poetic_name=ns_config["poetic_alias"],
            glyph=glyph,
            component_type=labels.get("app.kubernetes.io/component", "unknown")
        )
        
        # Write individual file
        filename = f"{function.replace('_', '-')}.yaml"
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(namespace_yaml)
            f.write(service_yaml)
        
        print(f"✓ Generated: {filepath}")
        
        all_namespaces.append(namespace_yaml)
        all_namespaces.append(service_yaml)
    
    # Write combined manifest
    combined_path = os.path.join(output_dir, "all-namespaces.yaml")
    with open(combined_path, "w", encoding="utf-8") as f:
        f.write("# Strategickhaos Linguistic Sovereignty - All Namespaces\n")
        f.write("# Generated with tripartite naming: Linear A ↔ Hebrew ↔ Egyptian\n")
        f.write("# ═" * 40 + "\n\n")
        for ns in all_namespaces:
            f.write(ns)
            f.write("\n")
    
    print(f"\n✓ Combined manifest: {combined_path}")
    print(f"\n🔥 Generated {len(k8s['namespaces'])} namespace manifests")


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate Kubernetes manifests with Linguistic Sovereignty naming"
    )
    parser.add_argument(
        "--output-dir", "-o",
        default="./generated_k8s",
        help="Output directory for manifest files (default: ./generated_k8s)"
    )
    parser.add_argument(
        "--seed", "-s",
        type=int,
        default=42,
        help="Random seed for reproducible naming (default: 42)"
    )
    
    args = parser.parse_args()
    
    print("🧠 LINGUISTIC SOVEREIGNTY - K8s Manifest Generator")
    print("═" * 50)
    print(f"Output directory: {args.output_dir}")
    print(f"Random seed: {args.seed}")
    print()
    
    generate_manifests(args.output_dir, args.seed)


if __name__ == "__main__":
    main()
