# auto_shutdown_idle.yml
# Ansible playbook: shutdown nodes that appear idle based on last output timestamp.
# Run from control plane periodically (cron / GitHub Action or control host).
- hosts: all_cloud_terminals
  become: yes
  gather_facts: yes
  vars:
    idle_minutes: 30       # threshold to consider node idle
    logs_dir: "/opt/strategickhaos/logs"
  tasks:
    - name: Find most recent log file timestamp
      shell: |
        if [ -d "{{ logs_dir }}" ]; then
          find "{{ logs_dir }}" -type f -name 'pid_ranco_*' -printf '%T@ %p\n' | sort -n | tail -n1 | cut -d' ' -f1
        else
          echo 0
        fi
      register: last_ts
      changed_when: false

    - name: Compute idle duration
      set_fact:
        last_epoch: "{{ (last_ts.stdout | default('0')) | float }}"
        now_epoch: "{{ ansible_date_time.epoch | int }}"
        idle_seconds: "{{ now_epoch - last_epoch | int }}"
        idle_minutes_actual: "{{ (idle_seconds / 60) | int }}"

    - name: Debug idle
      debug:
        msg: "Host {{ inventory_hostname }} idle {{ idle_minutes_actual }} minutes (threshold {{ idle_minutes }})."

    - name: Shutdown node if idle > threshold
      when: last_epoch != 0 and idle_minutes_actual >= idle_minutes
      block:
        - name: Schedule shutdown in 2 minutes
          shell: "nohup sudo shutdown -h +2 'Idle auto-shutdown by cloud-swarm cost-guard' >/dev/null 2>&1 &"
          async: 1
