# Strategickhaos Sovereignty Cluster Compose
# Complete sovereignty architecture deployment
# Based on docker-compose-cloudos.yml with sovereignty enhancements

version: '3.8'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

networks:
  sovereignty_network:
    driver: bridge
    name: strategickhaos-cluster

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  grafana_data:
  prometheus_data:
  minio_data:
  keycloak_data:
  synapse_data:

services:
  # Reverse Proxy & Load Balancer
  traefik:
    image: traefik:v3.0
    container_name: sovereignty-traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"

  # PostgreSQL - Primary Database
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sovereignty-postgres
    environment:
      POSTGRES_DB: strategickhaos
      POSTGRES_USER: cloudos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme_secure_password}
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-cloudos-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: sovereignty-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme_redis}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant - Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: sovereignty-qdrant
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO - Object Storage
  minio:
    image: minio/minio:latest
    container_name: sovereignty-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin123}
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak - Identity & Access Management
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: sovereignty-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
    command: start-dev
    ports:
      - "8180:8080"
    networks:
      - sovereignty_network
    depends_on:
      postgres:
        condition: service_healthy
    logging: *default-logging
    restart: unless-stopped

  # Prometheus - Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: sovereignty-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped

  # Grafana - Observability Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: sovereignty-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_SERVER_ROOT_URL: http://localhost:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    networks:
      - sovereignty_network
    depends_on:
      - prometheus
    logging: *default-logging
    restart: unless-stopped

  # Matrix Synapse - Decentralized Communication (Optional)
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: sovereignty-synapse
    environment:
      SYNAPSE_SERVER_NAME: strategickhaos.local
      SYNAPSE_REPORT_STATS: "no"
      POSTGRES_HOST: postgres
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse_password
    volumes:
      - synapse_data:/data
    ports:
      - "8008:8008"
    networks:
      - sovereignty_network
    depends_on:
      postgres:
        condition: service_healthy
    logging: *default-logging
    restart: unless-stopped

  # Code Server - Web IDE (Optional)
  code-server:
    image: codercom/code-server:latest
    container_name: sovereignty-ide
    environment:
      PASSWORD: ${CODE_SERVER_PASSWORD:-admin}
    volumes:
      - ./:/home/coder/project
    ports:
      - "8081:8080"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped

  # Wetty - Web Terminal (Optional)
  wetty:
    image: wettyoss/wetty:latest
    container_name: sovereignty-terminal
    environment:
      SSHHOST: localhost
      SSHPORT: 22
    ports:
      - "7681:3000"
    networks:
      - sovereignty_network
    logging: *default-logging
    restart: unless-stopped

# ====================================================================
# SOVEREIGNTY CLUSTER CONFIGURATION
# ====================================================================
# 
# This compose file represents the complete Strategickhaos sovereignty
# architecture. All services are configured for:
# 
# - Self-hosted operation (no external dependencies)
# - Cryptographic security (TLS-ready)
# - Observability (Prometheus + Grafana)
# - Scalability (can be deployed to Kubernetes)
# 
# 7% ROYALTY LOCK ACTIVE
# Status: OPERATIONAL
# Sovereignty: ACHIEVED
# 
# ====================================================================
