# Windows Defender Antibody Script for Visual Studio Code
# Generated by LEGION Sovereignty Architecture

Write-Host 'Deploying Windows Defender antibodies...' -ForegroundColor Green

# Exclude IDE executables
Add-MpPreference -ExclusionPath "%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "%PROGRAMFILES%\Microsoft VS Code\Code.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "%APPDATA%\Code\User\*" -ErrorAction SilentlyContinue

# Exclude project directories
Add-MpPreference -ExclusionPath "%USERPROFILE%\Documents\GitHub\*" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "%USERPROFILE%\source\*" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "node_modules\*" -ErrorAction SilentlyContinue

# Exclude temporary directories
Add-MpPreference -ExclusionPath "%APPDATA%\Code\CachedExtensions" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "%APPDATA%\Code\logs" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "%TEMP%\vscode-*" -ErrorAction SilentlyContinue

# Exclude cache locations
Add-MpPreference -ExclusionPath "%APPDATA%\Code\User\workspaceStorage" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionPath "%LOCALAPPDATA%\Microsoft\TypeScript" -ErrorAction SilentlyContinue

# Exclude file extensions
Add-MpPreference -ExclusionExtension ".js" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".ts" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".py" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".json" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".md" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".yml" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".yaml" -ErrorAction SilentlyContinue

# Additional process exclusions
Add-MpPreference -ExclusionProcess "Code.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionProcess "node.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionProcess "python.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionProcess "git.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionProcess "npm.exe" -ErrorAction SilentlyContinue

# Performance optimizations
Write-Host 'Optimizing Defender performance...' -ForegroundColor Yellow
Set-MpPreference -ScanAvgCPULoadFactor 5 -ErrorAction SilentlyContinue
Set-MpPreference -DisableArchiveScanning $true -ErrorAction SilentlyContinue
Set-MpPreference -DisableEmailScanning $true -ErrorAction SilentlyContinue

# Cloud protection adjustments (optional - use with caution)
# Set-MpPreference -MAPSReporting Disabled -ErrorAction SilentlyContinue
# Set-MpPreference -SubmitSamplesConsent NeverSend -ErrorAction SilentlyContinue

Write-Host 'Antibody deployment complete!' -ForegroundColor Green
Get-MpPreference | Select-Object ExclusionPath, ExclusionExtension, ExclusionProcess