# ============================================================================
# SOVEREIGNTY STACK SPECIFICATION v1.0
# ============================================================================
# A formal YAML specification for the self-verifying sovereign software stack.
#
# This specification defines the architecture, components, and validation
# requirements for a portable, self-verifying sovereign compute environment.
#
# Copyright (c) 2025 Strategickhaos DAO LLC
# SPDX-License-Identifier: MIT
# ============================================================================

apiVersion: sovereignty.strategickhaos.io/v1
kind: SovereigntyStack
metadata:
  name: strategickhaos-sovereignty-stack
  version: "1.0.0"
  description: |
    A portable, self-verifying sovereign compute environment that performs
    hash-proven integrity checks on critical stack files and validates
    execution readiness across a full cloud-to-local pipeline.
  maintainers:
    - name: Strategickhaos DAO LLC
      email: security@strategickhaos.io
  license: MIT
  repository: https://github.com/Strategickhaos/Sovereignty-Architecture-Elevator-Pitch-

spec:
  # ==========================================================================
  # STACK LAYERS
  # ==========================================================================
  layers:
    # Layer 0: Hardware/Boot
    - name: boot-layer
      level: 0
      description: Portable boot environment (USB/local device)
      components:
        - name: portable-runtime
          type: boot-device
          description: USB or local boot device for air-gapped operation
        - name: filesystem-structure
          type: os-layout
          description: Proto-operating system file structure

    # Layer 1: Platform Verification
    - name: platform-layer
      level: 1
      description: System environment validation
      components:
        - name: environment-validator
          type: diagnostic
          checks:
            - git-version
            - python-version
            - bash-version
            - docker-daemon
            - node-version
            - kubectl-availability

    # Layer 2: Integrity & Security
    - name: integrity-layer
      level: 2
      description: Tamper-evident security and integrity
      components:
        - name: hash-verifier
          type: security
          algorithm: SHA-256
          description: File hash verification for tamper detection
        - name: syntax-validator
          type: validation
          description: Script syntax validation (bash -n, py_compile)
        - name: sbom-generator
          type: supply-chain
          description: Software Bill of Materials generation

    # Layer 3: Configuration
    - name: config-layer
      level: 3
      description: Configuration and policy management
      components:
        - name: config-auditor
          type: audit
          files:
            - discovery.yml
            - docker-compose.yml
            - governance/access_matrix.yaml
        - name: policy-enforcer
          type: governance
          description: Access control and policy validation

    # Layer 4: Network
    - name: network-layer
      level: 4
      description: Network connectivity and external services
      components:
        - name: connectivity-diagnostic
          type: network
          endpoints:
            - github.com
            - api.github.com
            - registry.npmjs.org
            - pypi.org
        - name: offline-mode
          type: resilience
          description: Air-gapped operation capability

    # Layer 5: Cloud Integration
    - name: cloud-layer
      level: 5
      description: Cloud editor and deployment integration
      components:
        - name: codespaces-integration
          type: cloud-ide
          provider: github
        - name: kubernetes-deployment
          type: orchestration
          description: K8s manifest deployment

  # ==========================================================================
  # VALIDATION MODULES
  # ==========================================================================
  validation:
    modules:
      - name: file-integrity
        description: Verify critical file existence, content, and byte count
        script: verify_sovereignty.sh --quick
        required: true

      - name: syntax-validation
        description: Pre-flight script syntax validation
        checks:
          bash:
            command: "bash -n"
            files: "*.sh"
          python:
            command: "python3 -m py_compile"
            files: "*.py"
        required: true

      - name: environment-check
        description: Platform verification for execution readiness
        script: verify_sovereignty.sh --env
        required: true

      - name: network-diagnostic
        description: Network connectivity and failure detection
        script: verify_sovereignty.sh --network
        required: false  # Can operate offline

      - name: hash-verification
        description: SHA-256 tamper detection
        script: verify_sovereignty.sh --verify
        required: true

      - name: configuration-audit
        description: Configuration file validation
        script: verify_sovereignty.sh --audit
        required: true

  # ==========================================================================
  # CRITICAL FILES
  # ==========================================================================
  critical_files:
    core:
      - path: README.md
        description: Project documentation
        required: true
      - path: LICENSE
        description: MIT License
        required: true
      - path: SECURITY.md
        description: Security policy
        required: true
      - path: package.json
        description: Node.js dependencies
        required: true

    configuration:
      - path: discovery.yml
        description: Service discovery configuration
        required: false
      - path: docker-compose.yml
        description: Docker service definitions
        required: false
      - path: docker-compose-cloudos.yml
        description: CloudOS service stack
        required: false

    scripts:
      - path: verify_sovereignty.sh
        description: Main verification script
        required: true
        hash_verified: true
      - path: validate-config.sh
        description: Configuration validator
        required: true
      - path: status-check.sh
        description: Service status checker
        required: true
      - path: bootstrap/deploy.sh
        description: Deployment bootstrap
        required: true

    governance:
      - path: governance/access_matrix.yaml
        description: Access control matrix
        required: true
      - path: TRUST_DECLARATION.md
        description: Trust and provenance declaration
        required: true

  # ==========================================================================
  # SECURITY REQUIREMENTS
  # ==========================================================================
  security:
    integrity:
      algorithm: SHA-256
      baseline_file: .sovereignty_hashes.sha256
      verification_log: .sovereignty_verification.log

    supply_chain:
      sbom_format: CycloneDX
      sbom_file: sbom.yaml
      slsa_level: 2  # Aspiration: Build provenance

    access_control:
      rbac_enabled: true
      matrix_file: governance/access_matrix.yaml

    audit:
      logging_enabled: true
      log_file: .sovereignty_verification.log
      retention_days: 90

  # ==========================================================================
  # EXECUTION MODES
  # ==========================================================================
  execution_modes:
    online:
      description: Full stack with network connectivity
      features:
        - cloud-integration
        - remote-registry-access
        - live-updates

    offline:
      description: Air-gapped operation mode
      features:
        - local-validation
        - cached-dependencies
        - portable-execution

    portable:
      description: USB boot device execution
      features:
        - minimal-footprint
        - self-contained
        - tamper-evident

  # ==========================================================================
  # OUTPUTS
  # ==========================================================================
  outputs:
    logs:
      - name: verification-log
        path: .sovereignty_verification.log
        format: plaintext

    receipts:
      - name: hash-baseline
        path: .sovereignty_hashes.sha256
        format: sha256sum

    reports:
      - name: sbom
        path: sbom.yaml
        format: cyclonedx-yaml
