#!/usr/bin/env bash
# synthesis_pipeline.sh - Meta-Synthesis Pipeline Orchestrator
# StrategicKhaos DAO LLC - Cognitive-Legal Architecture
# IP Framework: DECLARATION-2025-12-02.md

set -euo pipefail
IFS=$'\n\t'

# === CONFIGURATION ===
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IP_FRAMEWORK="${IP_FRAMEWORK:-legal/DECLARATION-2025-12-02.md}"
OUTPUT_DIR="${OUTPUT_DIR:-./synthesis_output}"
TIMESTAMP="$(date -u +%Y%m%d_%H%M%S)"

# === COLORS ===
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# === LOGGING ===
log() { echo -e "${BLUE}[$(date +%H:%M:%S)]${NC} $*"; }
success() { echo -e "${GREEN}✅ $*${NC}"; }
warn() { echo -e "${YELLOW}⚠️  $*${NC}"; }
error() { echo -e "${RED}❌ $*${NC}"; exit 1; }

# === BANNER ===
print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║           META-SYNTHESIS PIPELINE v1.0                        ║"
    echo "║     GPT → Contradiction Engine → DAO Record → Notarize → Graph║"
    echo "║                                                               ║"
    echo "║     StrategicKhaos DAO LLC (2025-001708194)                   ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# === USAGE ===
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

META-SYNTHESIS PIPELINE
Chains: GPT → Contradiction Engine → DAO Record → Notarize → Graph

Options:
  -i, --inputs FILE1,FILE2,...   Comma-separated input files (required)
  -t, --topic TOPIC              Topic/title for the synthesis (required)
  -o, --output DIR               Output directory (default: ./synthesis_output)
  -f, --framework PATH           IP framework document path
  --skip-ipfs                    Skip IPFS pinning
  --skip-ots                     Skip OpenTimestamps
  --skip-graph                   Skip graph generation
  -h, --help                     Show this help message

Example:
  $0 -i gpt.txt,claude.txt -t "Sovereign Architecture Design"
  $0 --inputs nova.md,ollama.md --topic "API Specification" --skip-ipfs

EOF
    exit 0
}

# === STAGE 1: INPUT COLLECTION ===
stage_input_collection() {
    log "STAGE 1: Input Collection"
    
    mkdir -p "$OUTPUT_DIR/inputs"
    
    local input_count=0
    for input_file in "${INPUT_FILES[@]}"; do
        if [[ -f "$input_file" ]]; then
            cp "$input_file" "$OUTPUT_DIR/inputs/"
            input_count=$((input_count + 1))
            log "  → Collected: $input_file"
        else
            warn "  → Not found: $input_file"
        fi
    done
    
    if [[ $input_count -eq 0 ]]; then
        error "No valid input files found"
    fi
    
    success "Collected $input_count input files"
}

# === STAGE 2: CONTRADICTION RESOLUTION ===
stage_contradiction_resolution() {
    log "STAGE 2: Contradiction Resolution"
    
    local synthesized_file="$OUTPUT_DIR/synthesized_${TIMESTAMP}.md"
    
    # Create synthesized output with attribution header
    {
        echo "---"
        echo "title: \"$TOPIC\""
        echo "attribution: \"StrategicKhaos DAO LLC (2025-001708194)\""
        echo "ip_framework: \"$IP_FRAMEWORK\""
        echo "generated: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
        echo "pipeline: \"Meta-Synthesis Pipeline v1.0\""
        echo "---"
        echo ""
        echo "# $TOPIC"
        echo ""
        echo "**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "**IP Framework:** $IP_FRAMEWORK"
        echo "**Entity:** StrategicKhaos DAO LLC (2025-001708194)"
        echo ""
        echo "---"
        echo ""
    } > "$synthesized_file"
    
    # Process each input file
    for input_file in "$OUTPUT_DIR/inputs/"*; do
        if [[ -f "$input_file" ]]; then
            echo "## Source: $(basename "$input_file")" >> "$synthesized_file"
            echo "" >> "$synthesized_file"
            cat "$input_file" >> "$synthesized_file"
            echo "" >> "$synthesized_file"
            echo "---" >> "$synthesized_file"
            echo "" >> "$synthesized_file"
        fi
    done
    
    # Add synthesis metadata
    {
        echo "## Synthesis Metadata"
        echo ""
        echo "- **Input Count:** ${#INPUT_FILES[@]}"
        echo "- **Synthesis Timestamp:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "- **Pipeline Version:** 1.0.0"
        echo "- **Hash:** $(sha256sum "$synthesized_file" | cut -d' ' -f1)"
    } >> "$synthesized_file"
    
    SYNTHESIZED_FILE="$synthesized_file"
    success "Synthesis complete: $synthesized_file"
}

# === STAGE 3: DAO RECORD GENERATION ===
stage_dao_record() {
    log "STAGE 3: DAO Record Generation"
    
    local dao_record="$OUTPUT_DIR/dao_record_${TIMESTAMP}.yaml"
    
    cat > "$dao_record" << EOF
# DAO Synthesis Record
# Generated by Meta-Synthesis Pipeline
# StrategicKhaos DAO LLC

record:
  type: "synthesis"
  topic: "$TOPIC"
  timestamp: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  pipeline_version: "1.0.0"
  
entity:
  legal_name: "StrategicKhaos DAO LLC"
  entity_number: "2025-001708194"
  formation_jurisdiction: "Wyoming"
  framework: "SF0068"

ip_framework:
  document: "$IP_FRAMEWORK"
  version: "1.0.0"

synthesis:
  input_count: ${#INPUT_FILES[@]}
  inputs:
EOF

    # Add input file names
    for input_file in "${INPUT_FILES[@]}"; do
        echo "    - \"$(basename "$input_file")\"" >> "$dao_record"
    done

    cat >> "$dao_record" << EOF

output:
  synthesized_file: "$(basename "$SYNTHESIZED_FILE")"
  sha256: "$(sha256sum "$SYNTHESIZED_FILE" | cut -d' ' -f1)"

generated:
  by: "synthesis_pipeline.sh"
  timestamp: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF
    
    DAO_RECORD="$dao_record"
    success "DAO record generated: $dao_record"
}

# === STAGE 4: NOTARIZATION ===
stage_notarization() {
    log "STAGE 4: Cryptographic Notarization"
    
    local notary_manifest="$OUTPUT_DIR/notarization_${TIMESTAMP}.json"
    
    # Generate hashes
    local synth_hash=$(sha256sum "$SYNTHESIZED_FILE" | cut -d' ' -f1)
    local dao_hash=$(sha256sum "$DAO_RECORD" | cut -d' ' -f1)
    
    # Create manifest
    cat > "$notary_manifest" << EOF
{
  "notarization": {
    "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "session": "synthesis_${TIMESTAMP}",
    "pipeline_version": "1.0.0"
  },
  "topic": "$TOPIC",
  "artifacts": [
    {
      "name": "$(basename "$SYNTHESIZED_FILE")",
      "type": "synthesized_content",
      "sha256": "$synth_hash"
    },
    {
      "name": "$(basename "$DAO_RECORD")",
      "type": "dao_record",
      "sha256": "$dao_hash"
    }
  ],
  "ip_framework": {
    "document": "$IP_FRAMEWORK",
    "entity": "StrategicKhaos DAO LLC",
    "entity_number": "2025-001708194"
  },
  "ipfs": {
    "status": "${SKIP_IPFS:-false}" == "true" && echo "skipped" || echo "not_available"
  },
  "opentimestamps": {
    "status": "${SKIP_OTS:-false}" == "true" && echo "skipped" || echo "not_available"
  }
}
EOF
    
    NOTARY_MANIFEST="$notary_manifest"
    success "Notarization complete: $notary_manifest"
}

# === STAGE 5: GRAPH VISUALIZATION ===
stage_graph_visualization() {
    log "STAGE 5: Graph Visualization"
    
    if [[ "$SKIP_GRAPH" == "true" ]]; then
        warn "Graph generation skipped"
        return
    fi
    
    local graph_file="$OUTPUT_DIR/synthesis_graph_${TIMESTAMP}.dot"
    
    # Generate DOT graph
    cat > "$graph_file" << 'DOTHEAD'
digraph Synthesis_Pipeline {
    rankdir=TB;
    bgcolor="#0d1117";
    fontname="Courier New";
    fontsize=14;
    node [fontname="Courier New", fontsize=11, style=filled, penwidth=2];
    edge [color="#ff0066", penwidth=2];

    labelloc="t";
    fontcolor="#ffffff";

    // Input Sources
    subgraph cluster_inputs {
        label="Input Sources";
        color="#00ccff";
        fontcolor="#ffffff";
        style=filled;
        fillcolor="#1a1a2e";
DOTHEAD

    local i=1
    for input_file in "${INPUT_FILES[@]}"; do
        local base=$(basename "$input_file" | sed 's/[^a-zA-Z0-9]/_/g')
        echo "        Input_${i} [label=\"$(basename "$input_file")\", fillcolor=\"#0066ff\", fontcolor=\"#ffffff\"];" >> "$graph_file"
        i=$((i + 1))
    done

    cat >> "$graph_file" << 'DOTMID'
    }

    // Pipeline Stages
    ContradictionEngine [label="Contradiction\nEngine", fillcolor="#ff6600", fontcolor="#ffffff", shape=box];
    SynthesizedOutput [label="Synthesized\nOutput", fillcolor="#00cc00", fontcolor="#ffffff"];
    DAORecord [label="DAO\nRecord", fillcolor="#cc00ff", fontcolor="#ffffff"];
    Notarization [label="Cryptographic\nNotarization", fillcolor="#ffcc00", fontcolor="#000000"];
    IPFramework [label="IP Framework\n(DECLARATION-2025-12-02)", fillcolor="#ff0066", fontcolor="#ffffff", shape=box];

    // Edges
DOTMID

    # Add edges from inputs to contradiction engine
    i=1
    for input_file in "${INPUT_FILES[@]}"; do
        echo "    Input_${i} -> ContradictionEngine;" >> "$graph_file"
        i=$((i + 1))
    done

    cat >> "$graph_file" << 'DOTEND'
    ContradictionEngine -> SynthesizedOutput;
    SynthesizedOutput -> DAORecord;
    DAORecord -> Notarization;
    Notarization -> IPFramework [style=dashed, label="registered"];
}
DOTEND

    # Generate SVG if graphviz is available
    if command -v dot &> /dev/null; then
        local svg_file="$OUTPUT_DIR/synthesis_graph_${TIMESTAMP}.svg"
        dot -Tsvg "$graph_file" -o "$svg_file" 2>/dev/null && {
            success "Generated graph: $svg_file"
        } || {
            warn "SVG generation failed, DOT file available: $graph_file"
        }
    else
        warn "Graphviz not available, DOT file created: $graph_file"
    fi
    
    GRAPH_FILE="$graph_file"
    success "Graph visualization complete"
}

# === FINAL SUMMARY ===
print_summary() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║              META-SYNTHESIS PIPELINE COMPLETE                 ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Topic:${NC} $TOPIC"
    echo -e "${BLUE}Timestamp:${NC} $TIMESTAMP"
    echo -e "${BLUE}IP Framework:${NC} $IP_FRAMEWORK"
    echo ""
    echo -e "${BLUE}Generated Artifacts:${NC}"
    echo "  📄 Synthesized Content: $SYNTHESIZED_FILE"
    echo "  📋 DAO Record: $DAO_RECORD"
    echo "  🔐 Notarization: $NOTARY_MANIFEST"
    [[ -n "${GRAPH_FILE:-}" ]] && echo "  📊 Graph: $GRAPH_FILE"
    echo ""
    echo -e "${BLUE}Output Directory:${NC} $OUTPUT_DIR"
    echo ""
    echo "All artifacts are registered under DECLARATION-2025-12-02."
    echo ""
}

# === MAIN ===
main() {
    print_banner
    
    # Parse arguments
    INPUT_FILES=()
    TOPIC=""
    SKIP_IPFS="false"
    SKIP_OTS="false"
    SKIP_GRAPH="false"
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            -i|--inputs)
                IFS=',' read -ra INPUT_FILES <<< "$2"
                shift 2
                ;;
            -t|--topic)
                TOPIC="$2"
                shift 2
                ;;
            -o|--output)
                OUTPUT_DIR="$2"
                shift 2
                ;;
            -f|--framework)
                IP_FRAMEWORK="$2"
                shift 2
                ;;
            --skip-ipfs)
                SKIP_IPFS="true"
                shift
                ;;
            --skip-ots)
                SKIP_OTS="true"
                shift
                ;;
            --skip-graph)
                SKIP_GRAPH="true"
                shift
                ;;
            -h|--help)
                usage
                ;;
            *)
                error "Unknown option: $1"
                ;;
        esac
    done
    
    # Validate required arguments
    [[ ${#INPUT_FILES[@]} -eq 0 ]] && error "No input files specified. Use -i or --inputs."
    [[ -z "$TOPIC" ]] && error "No topic specified. Use -t or --topic."
    
    # Create output directory
    mkdir -p "$OUTPUT_DIR"
    
    # Execute pipeline stages
    stage_input_collection
    stage_contradiction_resolution
    stage_dao_record
    stage_notarization
    stage_graph_visualization
    
    # Print summary
    print_summary
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
