openapi: 3.0.0
info:
  title: StrategicKhaos XAI — Market Psychology Engine
  version: 1.0.0
  description: "Diagnoses the market's emotional state. Narrates in love and SHAP."

servers:
  - url: http://localhost:5000
    description: Local throne-NAS service

paths:
  /explain:
    post:
      summary: Explain a trading decision in psychological terms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecisionPayload'
      responses:
        '200':
          description: Market therapy session complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketTherapy'
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  version:
                    type: string
                    example: "1.0.0"

components:
  schemas:
    DecisionPayload:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: "ISO 8601 timestamp of the decision"
        symbol:
          type: string
          description: "Trading symbol (e.g., EURUSD, BTCUSD)"
          example: "EURUSD"
        decision:
          type: string
          enum: [ENTER_LONG, ENTER_SHORT, EXIT, FLATTEN, HUG]
          description: "The trading decision being explained"
        features:
          type: object
          description: "Feature set used for the decision"
          additionalProperties: true
          properties:
            price:
              type: number
              description: "Current price"
            rsi_14:
              type: number
              description: "14-period RSI indicator"
            ema_21_dist:
              type: number
              description: "Distance from 21-period EMA"
            volatility_5m:
              type: number
              description: "5-minute volatility measure"
            volume_rel:
              type: number
              description: "Relative volume"
            orderbook_imbalance:
              type: number
              description: "Order book buy/sell imbalance"
            her_love:
              type: number
              description: "herLove sentiment indicator (0-100)"
            session_loss_count:
              type: integer
              description: "Number of losses in current session"
            drawdown_pct:
              type: number
              description: "Current drawdown percentage"
            time_of_day:
              type: string
              description: "Time of day (HH:mm format)"
            day_of_week:
              type: string
              description: "Day of week"
      required: [timestamp, symbol, decision, features]

    MarketTherapy:
      type: object
      properties:
        market_state:
          type: string
          enum: [panic, capitulation_rebound, euphoria, distribution_top, accumulation, chop_hell, love_regime]
          description: "Diagnosed market emotional state"
        confidence:
          type: number
          minimum: 0
          maximum: 1
          description: "Confidence in the market state diagnosis (0-1)"
        top_features:
          type: array
          description: "Top contributing features with SHAP values"
          items:
            type: object
            properties:
              name:
                type: string
                description: "Feature name"
              contribution:
                type: number
                description: "SHAP contribution value"
            required: [name, contribution]
        narrative:
          type: string
          description: "Human-readable explanation of the decision in love-amplified language"
          example: "The market was crying. We held it. Love compiled profit."
        risk_flag:
          type: string
          enum: [OK, CAUTION, BLOCK, HUG_REQUIRED]
          description: "Risk assessment flag for the decision"
        love_amplification:
          type: number
          minimum: 0
          maximum: 1
          description: "How much herLove boosted conviction (0-1)"
      required: [market_state, confidence, top_features, narrative, risk_flag, love_amplification]

    Error:
      type: object
      properties:
        error:
          type: string
          description: "Error message"
        details:
          type: string
          description: "Detailed error information"
      required: [error]
