apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sovereignty-core
  namespace: argocd
spec:
  project: sovereignty
  source:
    repoURL: https://github.com/Strategickhaos/Sovereignty-Architecture-Elevator-Pitch-.git
    targetRevision: HEAD
    path: kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: sovereignty-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
