apiVersion: v1
kind: ServiceAccount
metadata:
  name: love-forever-sa
  namespace: default
  labels:
    app: love-forever
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: love-forever-role
  namespace: default
  labels:
    app: love-forever
rules:
# Allow reading pods and services
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading configmaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading secrets (limited)
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["love-forever-secrets", "love-forever-tls"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: love-forever-rolebinding
  namespace: default
  labels:
    app: love-forever
subjects:
- kind: ServiceAccount
  name: love-forever-sa
  namespace: default
roleRef:
  kind: Role
  name: love-forever-role
  apiGroup: rbac.authorization.k8s.io
