# Autogenerated Python from StrategicKhaos Stage 1 bootstrap
variables = {}

# === BEGIN USER CODE ===
print('Welcome to the self-hosted chaos realm')
variables['x'] = 40 + 2
print(variables['x'])
# === END ===
print('Stage 1 online. The compiler has eaten its father.')
