#!/usr/bin/env python3
"""
Standalone test for PsycheVille reflection generation
Tests the worker without Docker using local paths
"""

import sys
import os
from pathlib import Path

# Add current directory to path
sys.path.insert(0, str(Path(__file__).parent))

# Set up environment to use local paths
base_dir = Path(__file__).parent
os.environ['PSYCHEVILLE_CONFIG'] = str(base_dir / 'psycheville.yaml')

# Monkey-patch the config to use local paths for testing
import yaml

def create_test_config():
    """Create a test configuration with local paths"""
    config = {
        'name': 'PsycheVille',
        'version': '1.0.0',
        'departments': {
            'Tools_Refinery': {
                'description': 'Monitors tool creation, usage, and effectiveness',
                'log_path': str(base_dir / 'logs' / 'tools_refinery'),
                'obsidian_path': str(base_dir / 'obsidian_vault' / 'PsycheVille' / 'Departments' / 'Tools_Refinery'),
                'observation_patterns': [
                    {
                        'pattern': 'tool_created',
                        'extract': ['tool_name', 'timestamp', 'creator']
                    },
                    {
                        'pattern': 'tool_invoked',
                        'extract': ['tool_name', 'timestamp', 'parameters', 'result']
                    },
                    {
                        'pattern': 'tool_failed',
                        'extract': ['tool_name', 'timestamp', 'error']
                    }
                ],
                'reflection_questions': [
                    'Which tools are being used most frequently?',
                    'Which tools are failing and why?',
                    'Are there patterns in tool creation that suggest gaps in capabilities?',
                    'What tools haven\'t been used recently and should be deprecated?'
                ]
            }
        },
        'reflection': {
            'daily': {
                'enabled': False,  # Disable scheduled runs
                'time': '06:00',
                'departments': ['Tools_Refinery']
            }
        },
        'reports': {
            'format': 'markdown',
            'template': '''# PsycheVille Daily Reflection - {{date}}

## Department: {{department}}

### Observations
{{observations}}

### Patterns Detected
{{patterns}}

### Key Insights
{{insights}}

### Recommendations
{{recommendations}}

---
*Generated by PsycheVille Self-Observation System*
''',
            'sections': [
                {'name': 'Observations', 'description': 'Raw data from logs'},
                {'name': 'Patterns', 'description': 'Detected patterns and trends'},
                {'name': 'Insights', 'description': 'Analysis and interpretation'},
                {'name': 'Recommendations', 'description': 'Actionable suggestions'}
            ]
        },
        'storage': {
            'obsidian_vault_path': str(base_dir / 'obsidian_vault' / 'PsycheVille'),
            'log_retention_days': 30,
            'report_retention_days': 90
        }
    }
    return config

# Test the reflection worker
if __name__ == '__main__':
    print("="*70)
    print("PsycheVille Standalone Test")
    print("="*70)
    print()
    
    # Import the worker class
    from reflection_worker import ReflectionWorker
    
    # Create test config
    test_config = create_test_config()
    
    # Create temporary config file
    test_config_path = base_dir / 'test_config.yaml'
    with open(test_config_path, 'w') as f:
        yaml.dump(test_config, f)
    
    print(f"✓ Created test configuration: {test_config_path}")
    print()
    
    # Initialize worker with test config
    worker = ReflectionWorker(str(test_config_path))
    print("✓ Initialized ReflectionWorker")
    print()
    
    # Run single reflection manually
    print("Running reflection for Tools_Refinery...")
    print("-" * 70)
    
    dept_name = 'Tools_Refinery'
    dept_config = test_config['departments'][dept_name]
    
    # Monitor logs
    worker.monitor_logs(
        dept_name,
        dept_config['log_path'],
        dept_config.get('observation_patterns', [])
    )
    print(f"✓ Monitored logs from: {dept_config['log_path']}")
    
    # Analyze observations
    analysis = worker.analyze_observations(dept_name)
    print(f"✓ Analyzed {analysis['total_observations']} observations")
    print()
    
    print("Analysis Results:")
    print(f"  Total observations: {analysis['total_observations']}")
    print(f"  Patterns detected: {len(analysis['patterns'])}")
    if analysis['patterns']:
        for pattern, count in analysis['patterns'].items():
            print(f"    - {pattern}: {count}")
    print()
    
    # Generate report
    report = worker.generate_report(dept_name, analysis)
    print("✓ Generated reflection report")
    print()
    
    # Save report
    worker.save_report(dept_name, report)
    print("✓ Saved report to Obsidian vault")
    print()
    
    # Display the report
    print("="*70)
    print("GENERATED REPORT")
    print("="*70)
    print(report)
    print()
    
    # Clean up test config
    test_config_path.unlink()
    
    print("="*70)
    print("Test completed successfully!")
    print("="*70)
    print()
    print("Check the generated report at:")
    print(f"  {dept_config['obsidian_path']}/")
    print()
