#!/bin/bash
# cluster_pulse.sh
# Cloud Swarm Operations - Cluster Health Monitoring & Pulse
# Strategickhaos DAO LLC — Real-time Cluster Status Heartbeat
#
# Usage: ./cluster_pulse.sh <inventory_file> [output_file]
# Example: ./cluster_pulse.sh cloud_hosts.ini /opt/strategickhaos/uam/cluster_pulse.txt
#
# This script monitors the health of all cloud swarm nodes and
# outputs a status file for consumption by monitoring systems.

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Configuration
INVENTORY="${1:-}"
OUTPUT_FILE="${2:-/tmp/cluster_pulse.txt}"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
TIMEOUT_SECONDS=10

# Validate inputs
if [[ -z "$INVENTORY" ]]; then
    echo -e "${RED}❌ Usage: $0 <inventory_file> [output_file]${NC}"
    exit 1
fi

if [[ ! -f "$INVENTORY" ]]; then
    echo -e "${RED}❌ Inventory file not found: $INVENTORY${NC}"
    exit 1
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                    CLUSTER PULSE CHECK                       ║${NC}"
echo -e "${BLUE}║               Cloud Swarm Health Monitor                     ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to check host health
check_host_health() {
    local host="$1"
    
    # Test connectivity
    if ! ssh -o ConnectTimeout="$TIMEOUT_SECONDS" -o BatchMode=yes "$host" "echo ok" &>/dev/null; then
        echo "UNREACHABLE"
        return
    fi
    
    # Get system stats
    local stats
    stats=$(ssh -o ConnectTimeout="$TIMEOUT_SECONDS" -o BatchMode=yes "$host" \
        "echo \$(uptime | awk -F'load average:' '{print \$2}' | awk -F',' '{print \$1}')|\
         \$(free -m | awk '/Mem:/ {printf \"%.1f\", \$3/\$2*100}')|\
         \$(df -h / | awk 'NR==2 {print \$5}' | tr -d '%')|\
         \$(pgrep -c 'swarm|compute|worker' 2>/dev/null || echo 0)" 2>/dev/null) || {
        echo "ERROR"
        return
    }
    
    echo "$stats"
}

# Function to determine status from metrics
determine_status() {
    local load="$1"
    local mem_percent="$2"
    local disk_percent="$3"
    local jobs="$4"
    
    # Remove any whitespace
    load=$(echo "$load" | tr -d ' ')
    
    # Critical thresholds
    if awk "BEGIN {exit !($mem_percent > 95)}"; then
        echo "CRITICAL"
        return
    fi
    
    if [[ "$disk_percent" -gt 95 ]]; then
        echo "CRITICAL"
        return
    fi
    
    # Warning thresholds
    if awk "BEGIN {exit !($mem_percent > 85)}"; then
        echo "WARNING"
        return
    fi
    
    if [[ "$disk_percent" -gt 85 ]]; then
        echo "WARNING"
        return
    fi
    
    # Active if jobs running
    if [[ "$jobs" -gt 0 ]]; then
        echo "ACTIVE"
        return
    fi
    
    # Idle if low load
    if awk "BEGIN {exit !($load < 0.1)}"; then
        echo "IDLE"
        return
    fi
    
    echo "HEALTHY"
}

# Track statistics
TOTAL_HOSTS=0
HEALTHY_HOSTS=0
ACTIVE_HOSTS=0
WARNING_HOSTS=0
CRITICAL_HOSTS=0
UNREACHABLE_HOSTS=0
IDLE_HOSTS=0

# Initialize output
{
    echo "# CLUSTER PULSE - $TIMESTAMP"
    echo "# Generated by cluster_pulse.sh"
    echo ""
    echo "PULSE_TIMESTAMP=$TIMESTAMP"
    echo ""
    echo "# HOST STATUS"
} > "$OUTPUT_FILE"

# Process each host in inventory
while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip comments and empty lines
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    
    # Extract host (first field, ignore ansible variables)
    host=$(echo "$line" | awk '{print $1}')
    
    # Skip group headers
    [[ "$host" =~ ^\[ ]] && continue
    [[ -z "$host" ]] && continue
    
    ((TOTAL_HOSTS++)) || true
    
    echo -ne "${BLUE}🔍 Checking: $host... ${NC}"
    
    # Get health metrics
    health=$(check_host_health "$host")
    
    if [[ "$health" == "UNREACHABLE" ]]; then
        ((UNREACHABLE_HOSTS++)) || true
        echo -e "${RED}UNREACHABLE${NC}"
        echo "HOST_${host//./_}=UNREACHABLE" >> "$OUTPUT_FILE"
        continue
    fi
    
    if [[ "$health" == "ERROR" ]]; then
        ((WARNING_HOSTS++)) || true
        echo -e "${YELLOW}ERROR${NC}"
        echo "HOST_${host//./_}=ERROR" >> "$OUTPUT_FILE"
        continue
    fi
    
    # Parse metrics
    IFS='|' read -r load mem disk jobs <<< "$health"
    
    # Determine status
    status=$(determine_status "$load" "$mem" "$disk" "$jobs")
    
    case "$status" in
        CRITICAL)
            ((CRITICAL_HOSTS++)) || true
            echo -e "${RED}CRITICAL (load:$load mem:${mem}% disk:${disk}%)${NC}"
            ;;
        WARNING)
            ((WARNING_HOSTS++)) || true
            echo -e "${YELLOW}WARNING (load:$load mem:${mem}% disk:${disk}%)${NC}"
            ;;
        ACTIVE)
            ((ACTIVE_HOSTS++)) || true
            echo -e "${GREEN}ACTIVE (jobs:$jobs load:$load)${NC}"
            ;;
        IDLE)
            ((IDLE_HOSTS++)) || true
            echo -e "${YELLOW}IDLE (load:$load)${NC}"
            ;;
        *)
            ((HEALTHY_HOSTS++)) || true
            echo -e "${GREEN}HEALTHY (load:$load mem:${mem}% disk:${disk}%)${NC}"
            ;;
    esac
    
    # Write to output file
    echo "HOST_${host//./_}=$status|load=$load|mem=${mem}%|disk=${disk}%|jobs=$jobs" >> "$OUTPUT_FILE"
    
done < "$INVENTORY"

# Write summary to output file
{
    echo ""
    echo "# CLUSTER SUMMARY"
    echo "TOTAL_HOSTS=$TOTAL_HOSTS"
    echo "HEALTHY_HOSTS=$HEALTHY_HOSTS"
    echo "ACTIVE_HOSTS=$ACTIVE_HOSTS"
    echo "IDLE_HOSTS=$IDLE_HOSTS"
    echo "WARNING_HOSTS=$WARNING_HOSTS"
    echo "CRITICAL_HOSTS=$CRITICAL_HOSTS"
    echo "UNREACHABLE_HOSTS=$UNREACHABLE_HOSTS"
    echo ""
    echo "# CLUSTER HEALTH"
    
    # Calculate overall health percentage
    if [[ "$TOTAL_HOSTS" -gt 0 ]]; then
        reachable=$((TOTAL_HOSTS - UNREACHABLE_HOSTS))
        healthy=$((HEALTHY_HOSTS + ACTIVE_HOSTS))
        if [[ "$reachable" -gt 0 ]]; then
            health_percent=$((healthy * 100 / reachable))
        else
            health_percent=0
        fi
        echo "CLUSTER_HEALTH_PERCENT=$health_percent"
    else
        echo "CLUSTER_HEALTH_PERCENT=0"
    fi
    
} >> "$OUTPUT_FILE"

# Print summary
echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}📊 Cluster Pulse Summary${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "Total Hosts: $TOTAL_HOSTS"
echo -e "${GREEN}Healthy: $HEALTHY_HOSTS${NC}"
echo -e "${GREEN}Active: $ACTIVE_HOSTS${NC}"
echo -e "${YELLOW}Idle: $IDLE_HOSTS${NC}"
echo -e "${YELLOW}Warning: $WARNING_HOSTS${NC}"
echo -e "${RED}Critical: $CRITICAL_HOSTS${NC}"
echo -e "${RED}Unreachable: $UNREACHABLE_HOSTS${NC}"
echo ""
echo -e "📄 Output written to: $OUTPUT_FILE"
echo -e "⏰ Timestamp: $TIMESTAMP"
echo ""

# Exit with appropriate code
if [[ "$CRITICAL_HOSTS" -gt 0 ]]; then
    exit 2  # Critical
elif [[ "$WARNING_HOSTS" -gt 0 ]] || [[ "$UNREACHABLE_HOSTS" -gt 0 ]]; then
    exit 1  # Warning
else
    exit 0  # OK
fi
